### ISSUE TITLE
BBC: bleadperl 5.41.3 breaks say-0.02 (due smartmatch removal)

### ISSUE THREAD

**Issue by andk** [bayashi/say#1]
Sample fail report: http://www.cpantesters.org/cpan/report/7d32a79e-6a36-11ef-9146-6d5afed1b116

**Comment by bayashi** [comment]
@andk Thanks! I fixed this for 5.41.3
http://matrix.cpantesters.org/?dist=say%200.04;perl=5.41.3;reports=1
